# 2018 Resolution is to do one Project Eular problem every single day.

# ----------------------------------------------------------------------------

# # Problem 1 (January 1, 2018)
# # If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.

# # Find the sum of all the multiples of 3 or 5 below 1000.
# sum = 0
# n = 0

# 1000.times do
#   if n %3 == 0 || n % 5 == 0
#     sum = sum + n 
#     p sum
#   else

#   end
#     n += 1
# end
# p sum

# ----------------------------------------------------------------------------

# Problem 2 (January 2, 2018)

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

arr = [1, 2]

30.times do
  new_value = arr.last + (arr[-2])
  arr << new_value

end 

sum = 0
i = 0
arr.length.times do
  if arr[i] %2 === 0 
    sum += arr[i]
    
  else
  end
  i +=1 
end

p sum













